- name: install yum repo with zookeeper
  yum: 
    name: https://archive.cloudera.com/cdh5/one-click-install/redhat/7/x86_64/cloudera-cdh-5-0.x86_64.rpm
    state: present

- name: install zookeeper
  yum:
    name: zookeeper-server
    state: present

- name: Check if Zookeeper has been initialized
  stat: path={{ zookeeper_data_dir }}/myid
  register: zookeeper_id_file

- name: Determine zookeeper id 
  set_fact: 
    zookeeper_myid: "{{ druid_zookeeper_hosts | selectattr('zk_host',  'match', '^'+ansible_fqdn+'$') | map(attribute='zk_id') | list | first }}"

- name: Initialize Zookeeper
  command: "service zookeeper-server init --force --myid={{ zookeeper_myid }}"
  when: not zookeeper_id_file.stat.exists
  notify:
    - Restart Zookeeper

- name: Configure Zookeeper
  template: src=zoo.cfg.j2 dest={{ zookeeper_conf_dir }}/zoo.cfg
  notify:
    - Restart Zookeeper

- name: Configure SERVER_JVMFLAGS
  lineinfile: dest=/etc/default/zookeeper
              regexp="SERVER_JVMFLAGS"
              line="export SERVER_JVMFLAGS=\"{{ zookeeper_server_jvmflags }}\""
  notify:
    - Restart Zookeeper

- name: Enable and start the Zookeeper service
  service: name=zookeeper-server enabled=yes state=started

