---
- hosts: 127.0.0.1
  vars_files:
    - vars/cluster.yml
  connection: local
  roles:
    - role: security-groups
    - role: container-node

  post_tasks:

    - name: Refresh EC2 cache
      command: hosts/ec2.py --refresh-cache
    
    - name: Refresh inventory
      meta: refresh_inventory


